name: Release Automation

on:
  push:
    tags:
      - 'v*'  # Trigger only when tags matching 'v*' are pushed

permissions:
  contents: write  # Grant write access for creating releases and uploading artifacts

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: poetry run pytest

      # Step 5: Generate Build Artifacts
      - name: Build Artifacts
        run: poetry build

      # Step 6: Generate Changelog
      - name: Generate Changelog
        id: changelog
        run: |
          echo "## Changelog" > changelog.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s" >> changelog.md

      # Step 7: Create Release on GitHub
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          artifacts: dist/*
